spring.application.name=MicroservicesProjectHotel
server.port=8082

spring.datasource.url:jdbc:postgresql://localhost:5432/Microservices
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# This properties basically show  the output on the  console 
spring.hibernate.show-sql:true 
# This propweerties  generally created the entity if required  and not created  by  us  
spring.jpa.hibernate.ddl-auto=update  


eureka.instance.prefer-ip-address=true
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=http://localhost:8084/eureka/


spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB

gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash:generateContent



cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}